apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-code-review
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: attest
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "*"
        type: Cosign 
        verifyDigest: true
        attestations:
          - predicateType: https://example.com/CodeReview/v1
            attestors:
            - entries:
              - keys:
                  publicKeys: |-
                    -----BEGIN PUBLIC KEY-----
                    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExtjNqfMhLnSKJWXQVpHnji/CK0/b
                    Lkd/9O1YBvu1XspKmcKvLZJJJYqkcy6VM6DN3rnJ0GhYC7ZcqvHvOUaHGw==
                    -----END PUBLIC KEY-----
            conditions:
              - all:   
                - key: "{{ .attestations[0].predicate.commit_id }}"
                  operator: Equals
                  value: "{{ .attestations[0].predicate.commit_id }}"  # This assumes the attestation will have this field.
                - key: "{{ .attestations[0].predicate.author_name }}"
                  operator: Equals
                  value: "DHEEMAN2912"
                - key: "{{ .attestations[0].predicate.author_email }}"
                  operator: Equals
                  value: "dheemandass2912@gmail.com"
                - key: "{{ .attestations[0].predicate.branch }}"
                  operator: Equals
                  value: "test"
                - key: "{{ .attestations[0].predicate.uri }}"
                  operator: Equals
                  value: "https://github.com/DHEEMAN2912/spring-petclinic"
