# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      security-events: write
      id-token: write
      contents: read
      attestations: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven Wrapper
        run: |
          pwd
          ./mvnw -B package > app.jar
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./app.jar

      - name: verify jar attesttion
        env:
          GH_TOKEN: ${{secrets.CR_Password}}
        run: |
          gh attestation verify app.jar --owner sachinmaniyar --format=json | jq .
  Sonar_And_Sbom_Generation:
    runs-on: ubuntu-latest
    env:
      AppName: 'spring-petclinic'
    strategy:
      matrix:
        java: [ '17' ]
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17          
      
      - name: Install Syft
        run: |
          curl -sSL https://github.com/anchore/syft/releases/download/v0.66.0/syft_0.66.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft
      - name: Generate SBOM with Syft
        # id: generate_sbom
        run: |
          # echo "result=`syft dir:. -o cyclonedx-json > sbom.json`" >> $GITHUB_ENV
          syft dir:. -o cyclonedx-json > sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v1
        with:
          subject-path: ./sbom.json
          sbom-path: ./sbom.json

      - name: verify SBOM attestation
        env:
          GH_TOKEN: ${{secrets.CR_Password}}
        run: |
          gh attestation verify ./sbom.json --owner sachinmaniyar --format=json | jq .
  Image_Build_And_Scan:
    runs-on: ubuntu-latest
    env:
      AppName: 'spring-petclinic'
    steps:    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis 
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17     
      - name: Build Docker Image
        run: ./mvnw spring-boot:build-image
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CR_Username }}
          #username: ${{ github.actor }}
          password: ${{ secrets.CR_Password }}
          #password: ${{secrets.GH_TOKEN}}
          registry: ghcr.io

      - name: Tag Docker Image
        run: |
          docker tag docker.io/library/${{ env.AppName }}:3.3.0-SNAPSHOT ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
      - name: Push Docker Image
        run: |
          docker push ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/sachinmaniyar/${{ env.AppName }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  sign:
    name: Sign Container Image
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: Image_Build_And_Scan
    env:
      AppName: 'spring-petclinic'
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download file artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CR_Username }}
          #username: ${{github.actor}}
          password: ${{ secrets.CR_Password }}
          #password: ${{secrets.GH_TOKEN}}
          registry: ghcr.io
          
      - name: Install Cosign CLI
        run: |
          curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
          chmod +x /usr/local/bin/cosign
          cosign version
      - name: sign container image
        run: |
          cosign sign --key env://COSIGN_KEY ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes
        shell: bash
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
        
      - name: Public Key Creation
        run: |
          cosign public-key --key env://COSIGN_KEY > cosign.pub
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
        
      - name: Verify Docker Image Signature
        run: |
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . #--insecure-ignore-tlog #--check-claims=false
      - name: Attach SBOM
        id: attach-sbom
        run: |
          set -e  # Exit on error
          # Run the cosign attach sbom command and capture its output
          output=$(cosign attach sbom --sbom sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to run cosign attach sbom"; exit 1; }
          echo "cat output --> showing output below"
          echo "output: $output"
          # Extract the SHA from the output
          sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
          echo "sbom_filename: $sbom_filename"
          # Check if the extraction was successful
          if [ -z "$sbom_filename" ]; then
            echo "Error: No SBOM filename found in the output"
            exit 1
          fi
          # Set the extracted SHA as an environment variable
          echo "SBOM_FILENAME=$sbom_filename" >> $GITHUB_ENV
      - name: Sign the SBOM attached with the Image
        run: |
          set -e  # Exit on error
          # Use the environment variable to construct the command
          if [ -z "$SBOM_FILENAME" ]; then
            echo "Error: SBOM_FILENAME environment variable is not set"
            exit 1
          fi
          echo "Signing SBOM with filename: $SBOM_FILENAME"
          cosign sign --key env://COSIGN_KEY ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME --yes || { echo "Failed to sign with SBOM"; exit 1; }
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
        

      - name: Verify Sign of SBOM attached with the Image
        run: |
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          set -e  # Exit on error
          cosign verify --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:$SBOM_FILENAME | jq . || { echo "Failed to verify SBOM Sign"; exit 1; }
      - name: Directly attest SBOM with the Image
        run: |
          set -e  # Exit on error
          # output=$(cosign attest --key env://COSIGN_KEY --type cyclonedx --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
          output=$(cosign attest --key env://COSIGN_KEY --predicate sbom.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest sbom with the image"; exit 1; }
          echo "output: $output"
        shell: bash

        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
        

      - name: Verfiy the attested Image
        run: |
          set -e  # Exit on error
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          # output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq -r .payload | base64 -D | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
          output1=$(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
          echo "output: $output1"
      - name: Sign SBOM
        run: |
          # set -e  # Exit on error
          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 #| jq -r .payload | base64 --decode | jq . 2>&1 #|| { echo "Failed to sign the blob"; exit 1; }
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}

      - name: upload Signed SBOM to Github Registry
        run: |
          # set -e  # Exit on error
          output2=$(cosign upload blob -f cosign.bundle ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
          echo "output: $output2"
          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
          echo "sbom_file: $sbom_file"
      - name: Verify SBOM Uploaded to Image Repo
        run: |
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          cosign verify-blob sbom.json --bundle cosign.bundle --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/sachinmaniyar/${{ env.AppName }} --certificate-github-workflow-trigger=push --key cosign.pub 2>&1 #| jq -r .payload | base64 --decode | jq .
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}

      - name: Fetch commit details
        run: |
          # Get the commit ID
          COMMIT_ID=$(git rev-parse HEAD)
          # Get the branch name
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          # Get the author name and email
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          # Get the pull request number from GitHub context if it's a PR
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          else
            PR_NUMBER="Not applicable"
          fi
          # Get the GitHub repository URL
          REPO_URL="https://github.com/${{ github.repository }}"
          # Create JSON output
          OUTPUT=$(jq -n \
            --arg commit_id "$COMMIT_ID" \
            --arg author_name "$AUTHOR_NAME" \
            --arg author_email "$AUTHOR_EMAIL" \
            --arg branch "$BRANCH_NAME" \
            --arg uri "$REPO_URL" \
            '{
              commit_id: $commit_id,
              author_name: $author_name,
              author_email: $author_email,
              branch: $branch,
              uri: $uri
            }')
          # Save JSON output to a file
          echo "$OUTPUT" > output.json
          # Print the contents of the JSON file
          cat output.json
      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with:
          name: git-details
          path: output.json
  # Sbom_Upload:
  #   runs-on: ubuntu-latest
  #   needs: Sonar_And_Sbom_Generation
  #   steps:
  #     - name: Check Out Source Code
  #       uses: actions/checkout@v3     
  #     - name: Download file artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sbom
  #     - name: Download shell script from Gist
  #       run: |
  #         cat sbom.json 
  #         curl -o project_creation_sbom_upload.sh https://gist.githubusercontent.com/SachinManiyar/20e5a000b24e257181228c6b3c46c004/raw/755ef0f37f0edcaa93464713daf2866a8dadcc1d/project_creation_sbom_upload.sh
  #     - name: Make the script executable
  #       run: chmod +x project_creation_sbom_upload.sh

  #     - name: Run the shell script
  #       run: ./project_creation_sbom_upload.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -v ${{ secrets.V_SCORE }}
 
  # vulnerability_score:
  #   runs-on: ubuntu-latest
  #   needs: Sbom_Upload
  #   #if: false
  #   steps:
  #     - name: Check Out Source Code
  #       uses: actions/checkout@v3     
  #     - name: Checkout code
  #       uses: actions/checkout@v3
      
  #     - name: Download shell script from Gist
  #       run: |
  #         curl -o vulnerability_score.sh https://gist.githubusercontent.com/SachinManiyar/50c889020f611cc0e2bad3543396992a/raw/b13972079aa046ffc7ecbc4e49c9888d107718e6/vulnerability_score.sh
  #     - name: Make the script executable
  #       run: chmod +x vulnerability_score.sh

  #     - name: Run the shell script
  #       run: ./vulnerability_score.sh -u ${{ secrets.URL_SCORE }} -t ${{ secrets.T_SCORE }} -p ${{ secrets.P_SCORE }} -d ${{ secrets.D_SCORE }} -v ${{ secrets.V_SCORE }}
   
  Attest_Verify_Predicate:
    permissions:
      security-events: write
      id-token: write
      contents: read
      attestations: write
      packages: write
    runs-on: ubuntu-latest
    env:
      AppName: 'spring-petclinic'
    needs: sign
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Download output.json file artifact
        uses: actions/download-artifact@v3
        with:
          name: git-details

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CR_Username }}
          #username: ${{github.actor}}
          password: ${{ secrets.CR_Password }}
          #password: ${{secrets.GH_TOKEN}}
          registry: ghcr.io

      - name: Install Cosign CLI
        run: |
          curl -sSL -o /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v2.2.3/cosign-linux-amd64
          chmod +x /usr/local/bin/cosign
          cosign version
      - name: Public Key Creation
        run: |
          cosign public-key --key env://COSIGN_KEY > cosign.pub
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}

      - name: Attestation using Predicate
        run: |
          cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes
          # $(cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
          # $(cat output.json | cosign attest --predicate - ghcr.io/sachinmaniyar/${{ env.AppName }}:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSPHRASE}}
        
      - name: Verify Predicate Attestation
        run: |
          docker inspect ghcr.io/sachinmaniyar/${{ env.AppName }}:latest
          cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/sachinmaniyar/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest | jq -r .payload | base64 --decode | jq .
          # $(cosign verify-attestation --key cosign.pub ghcr.io/sachinmaniyar/${{ env.AppName }}:latest 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
  Deploy_To_Aks:
    runs-on: ubuntu-latest
    needs: Attest_Verify_Predicate
    env:
      RESOURCE_GROUP: 'K8SDemo'
      CLUSTER_NAME: 'K8SDemo'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

        # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'       
      - name: Deploy to AKS
        run: |
          kubectl apply -f K8s/deployment.yaml
          kubectl apply -f K8s/service.yaml
